version: "3"
services:
  acme-explorer:
    container_name: "acme-explorer-dev"
    image: "alejuarob/acme-explorer"
    networks:
      dev-network:
    volumes:
      - "logsvol:/usr/src/app/logs"
    restart: on-failure
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - DBPORT=${DBPORT}
      - DBNAME=${DBNAME}
      - DBHOST=${DBHOST}
      - PORT=${PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${PORT}
      - FRONT_PORT=${FRONT_PORT}
  mongo:
    image: "mongo"
    command: --port ${DBPORT} --logpath /var/log/mongodb/mongodb.log
    networks:
      dev-network:
        aliases:
          - "mongo${DBPORT}"
    volumes:
      - "datavol:/data/db"
      - "logsvol:/var/log/mongodb"

volumes:
  datavol:
  logsvol:
    external: true

networks:
  dev-network:
    external: true
