{
 "title": "Dashboard Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top10Keywords",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "top10Keywords",
     "query": "SELECT \"top1\", \"top2\", \"top3\", \"top4\", \"top5\",\"top6\", \"top7\", \"top8\", \"top9\", \"top10\" FROM \"top10Keywords\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "top1" ], "type": "field" }
      ],
      [
       { "params": [ "top2" ], "type": "field" }
      ],
      [
       { "params": [ "top3" ], "type": "field" }
      ],
      [
       { "params": [ "top4" ], "type": "field" }
      ],
      [
       { "params": [ "top5" ], "type": "field" }
      ],
      [
       { "params": [ "top6" ], "type": "field" }
      ],
      [
       { "params": [ "top7" ], "type": "field" }
      ],
      [
       { "params": [ "top8" ], "type": "field" }
      ],
      [
       { "params": [ "top9" ], "type": "field" }
      ],
      [
       { "params": [ "top10" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio by status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "ratioByStatus",
     "select": [
      [
       { "params": [ "ratio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of applications per trip  (Avg, min, max, std)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "applicationsPerTrip",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "std" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Trips per Manager  (Avg, min, max, std)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "tripsPerManager",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "std" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Price per trip (Avg, min, max, std)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pricePerTrip",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "std" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Price range from Users Finders",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pricePerFinder",
     "select": [
      [
       { "params": [ "avgMaxPrice" ], "type": "field" }
      ],
      [
       { "params": [ "avgMinPrice" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}