name: Continous Integration

on:
  push:
    branches: [main]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          collectionPath: ./postmanCollection/Acme-explorer-test-e2e.postman_collection.json
      - run: npm install -g newman
      - run: newman run ${{collectionPath}}

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
